baseURL = ""
languageCode = "de"
DefaultContentLanguage = "de"

disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

relativeURLs = true
canonifyURLs = false
uglyURLs = false
permalinks = ":slug"
pygmentsCodeFences = true
pygmentsStyle = "manni"
pygmentsUseClasses = true


theme = "speedataweb"

title = "speedata Handbuch"

[params]
  type = "handbuch"


[markup.goldmark.renderer]
unsafe = true
